AMM Register
Autonomous-Finance/amm-monitor pull request #7
Opened 2024-07-29 09:59 UTC by micovi

2024-07-29 10:39 UTC, dvinubius requested changes

2024-07-29 10:39 UTC, dvinubius commented on process.lua
> +  function(msg)
Let's rather keep one handler for payments from dexi-subscribers and create another one for payments from amm-registrators

```lua
Handlers.add(
  "Receive-Payment-For-Subscriber",
  function(msg)
    return Handlers.utils.hasMatchingTag("Action", "Credit-Notice")(msg)
        and Handlers.utils.hasMatchingTag("X-Action", "Pay-For-Subscriptions")(msg)
        and msg.From == PAYMENT_TOKEN_PROCESS
  end,
  function(msg)
    subscriptions.recordPayment(msg)
  end
)

Handlers.add(
  "Receive-Payment-For-AMM-Registration",
  function(msg)
    return Handlers.utils.hasMatchingTag("Action", "Credit-Notice")(msg)
        and Handlers.utils.hasMatchingTag("X-Action", "Register-AMM")(msg)
        and msg.From == PAYMENT_TOKEN_PROCESS
  end,
  function(msg)
    register_amm.handleRegisterAMM(msg)
    -- no need to do subscriptions.recordPayment(...) since that one is just for the subscribers to Dexi data
  end
)
```

2024-07-29 10:39 UTC, dvinubius commented on register-amm/register-amm.lua
> +
There should be an "await" here, because the AMM will error if the payment arrives before the subscriber registration is finished. This can happen due to the lack of an ordering guarantee for the 2 messages here.

It would be awesome to have aos 2.0 published ASAP, so that the code here can stay simple and to the "await" part...

2024-07-29 10:39 UTC, dvinubius commented on register-amm/register-amm.lua
> +
Otherwise we'll need to write this as a 2 step state machine :\

2024-07-29 10:39 UTC, dvinubius commented on register-amm/register-amm.lua
> +        ['Topics'] = json.encode({ "order-confirmation", "liquidity-change" })
`liquidity-change` was the initial idea, but it's rather `swap-params-change`, because both reserves and the fee are relevant -> together they are the swap params.

I'll have to update the topic `liquidity-change` in `bark-amm` for this to work, but we should keep it accurate I think

2024-07-30 04:46 UTC, micovi commented on register-amm/register-amm.lua
> +        ['Topics'] = json.encode({ "order-confirmation", "liquidity-change" })
So should I go with the change of `liquidity-change` into `swap-params-change` ?

2024-07-30 09:32 UTC, dvinubius commented on register-amm/register-amm.lua
> +        ['Topics'] = json.encode({ "order-confirmation", "liquidity-change" })
yes

2024-08-01 13:44 UTC, closed without merging